DROP PROCEDURE IF EXISTS `SP_SEL_CATEGORY_COUNT`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_CATEGORY_COUNT`(OUT `o_count` INT UNSIGNED) NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER

BEGIN
	SELECT COUNT(1)
	INTO o_count
	FROM `co_category`;
END$$
# change the delimiter back to semicolon
DELIMITER ;