DROP PROCEDURE IF EXISTS `SP_SEL_ALL_SERVERS_WITHOUT_ID`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_ALL_SERVERS_WITHOUT_ID`() NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER
BEGIN
	SELECT `se_name`, `se_url`
	FROM   `co_servers`
	ORDER BY `se_created` ASC;
END$$
# change the delimiter back to semicolon
DELIMITER ;