DROP PROCEDURE IF EXISTS `SP_SEL_SERVERS_COUNT`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_SERVERS_COUNT`(OUT `se_count` INT UNSIGNED) NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER
BEGIN
	SELECT COUNT(1)
    INTO   se_count
	FROM   `co_servers`;
END$$
# change the delimiter back to semicolon
DELIMITER ;