DROP PROCEDURE IF EXISTS `SP_SEL_EMOTICON_COUNT`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_EMOTICON_COUNT`(OUT `em_count` INT UNSIGNED) NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER

BEGIN 
	SELECT COUNT(1)
	INTO `em_count` 
	FROM `co_emoticon`;
END$$
# change the delimiter back to semicolon
DELIMITER ;