DROP PROCEDURE IF EXISTS `SP_SEL_USER_COUNT`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_USER_COUNT`(OUT `o_total` INT UNSIGNED) NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER
BEGIN
	SELECT COUNT(1)
	INTO o_total
	FROM `co_user`;
END$$
# change the delimiter back to semicolon
DELIMITER ;